version: '3.8'

services:
  server:
    build: .
    container_name: myos_server
    ports:
      - "8080:8000"
    volumes:
      - .:/app
      - ./credentials.json:/app/credentials.json
      - ./token.json:/app/token.json
    environment:
      - MONGODB_URL=mongodb://mongo:27017
      - CHROMA_HOST=chromadb
    depends_on:
      - mongo
      - chromadb
    command: uvicorn server:app --host 0.0.0.0 --port 8000 --reload

  mongo:
    image: mongo:latest
    container_name: myos_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  chromadb:
    image: chromadb/chroma:latest
    container_name: myos_rag
    ports:
      - "8001:8000"
    volumes:
      - chroma_data:/chroma/chroma

  n8n:
    image: n8nio/n8n:latest
    container_name: myos_n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://genetic-garlicky-thurman.ngrok-free.dev # הכתובת שמצאת!
    volumes:
      - n8n_data:/home/node/.n8n

  waha:
    image: devlikeapro/waha
    container_name: myos_waha
    restart: always
    environment:
      - WHATSAPP_DEFAULT_ENGINE=WEBJS
      - WHATSAPP_RESTART_ON_FAIL=True
      - WHATSAPP_DISABLE_WEB_PAGE_PREVIEW=True
      - WAHA_DASHBOARD_USERNAME=admin
      - WAHA_DASHBOARD_PASSWORD=a89ab8c73de84322832c5fa6c9602177
      - WAHA_API_KEY=secret
    ports:
      - "3000:3000"
    volumes:
      - ./waha_sessions:/app/sessions

  ngrok:
    image: ngrok/ngrok:latest
    container_name: myos_tunnel
    restart: unless-stopped
    command: "http n8n:5678"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    ports:
      - 4040:4040
    depends_on:
      - n8n

volumes:
  mongo_data:
  chroma_data:
  n8n_data:
