version: '3.8'

services:
  server:
    build: .
    container_name: myos_server
    ports:
      - "8080:8000"
    volumes:
      - .:/app
      - ./credentials.json:/app/credentials.json
      - ./token.json:/app/token.json
    environment:
      - MONGODB_URL=mongodb://mongo:27017
      - CHROMA_HOST=chromadb
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - TZ=Asia/Jerusalem
    env_file:
      - .env
    depends_on:
      - mongo
      - chromadb
    command: python main.py

  mongo:
    image: mongo:latest
    container_name: myos_mongo
    command: [ "mongod", "--quiet", "--logpath", "/dev/null" ]
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  chromadb:
    image: chromadb/chroma:latest
    container_name: myos_rag
    ports:
      - "8001:8000"
    volumes:
      - chroma_data:/chroma/chroma

  n8n:
    image: n8nio/n8n:latest
    container_name: myos_n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=${N8N_WEBHOOK_URL:-http://localhost:5678}
      - TZ=Asia/Jerusalem
    volumes:
      - n8n_data:/home/node/.n8n

  ngrok:
    image: ngrok/ngrok:latest
    container_name: myos_tunnel
    restart: unless-stopped
    command: "http n8n:5678"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    ports:
      - 4040:4040
    depends_on:
      - n8n

volumes:
  mongo_data:
  chroma_data:
  n8n_data:
